import { ArrowLeft, ArrowRight, CalendarDays, Info } from 'lucide-react';
import { useState } from 'react';
import { useLocation } from 'wouter';
import { loadCases, saveCases, type CaseRecord } from '@/data/casework';
import { DocumentUploader } from './DocumentUploader';

export function CaseForm() {
  const [, setLocation] = useLocation();
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', category: 'Investment platform', description: '', amountInvolved: '', incidentDate: '', institution: '', additionalNotes: '' });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!form.title || !form.description || !form.institution) { setError('Add a title, institution, and clear description before continuing.'); return; }
    setSaving(true); setError('');
    const id = `CW-${Math.floor(24030 + Math.random() * 500)}`;
    const newCase: CaseRecord = { ...form, id, amountInvolved: Number(form.amountInvolved) || 0, submittedDate: new Date().toISOString().slice(0, 10), status: 'Submitted', lastUpdate: new Date().toISOString().slice(0, 10), assignedReviewer: 'Pending assignment', notes: form.additionalNotes || 'Your case is in the intake queue.' };
    saveCases([newCase, ...loadCases()]);
    window.setTimeout(() => setLocation(`/dashboard/cases/${id}`), 500);
  };
  const input = 'mt-2 w-full rounded-xl border border-input bg-card px-3.5 py-3 text-sm text-foreground outline-none transition placeholder:text-muted-foreground/65 focus:border-teal-600 focus:ring-4 focus:ring-teal-100';
  return <form onSubmit={submit} className="space-y-7" data-testid="form-new-case">
    <div className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-800"><Info size={18} /></span><div><h2 className="font-display text-xl font-extrabold">Tell us what happened</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Start with the facts you know. You can add more detail and documents after submitting.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-bold">Case title<input className={input} value={form.title} onChange={(event) => update('title', event.target.value)} placeholder="A short description of the issue" data-testid="input-case-title" /></label><label className="text-sm font-bold">Case category<select className={input} value={form.category} onChange={(event) => update('category', event.target.value)} data-testid="select-case-category"><option>Investment platform</option><option>Card payment</option><option>Bank transfer</option><option>Digital asset transfer</option><option>Other financial matter</option></select></label><label className="text-sm font-bold">Institution or platform<input className={input} value={form.institution} onChange={(event) => update('institution', event.target.value)} placeholder="Name of the business or bank" data-testid="input-institution" /></label><label className="text-sm font-bold">Amount involved<input type="number" min="0" className={input} value={form.amountInvolved} onChange={(event) => update('amountInvolved', event.target.value)} placeholder="0" data-testid="input-amount" /></label><label className="text-sm font-bold">Incident date<div className="relative"><input type="date" className={input} value={form.incidentDate} onChange={(event) => update('incidentDate', event.target.value)} data-testid="input-incident-date" /><CalendarDays size={16} className="pointer-events-none absolute right-3 top-5 text-muted-foreground" /></div></label><label className="sm:col-span-2 text-sm font-bold">What happened?<textarea className={`${input} min-h-36 resize-y`} value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="Share the timeline, what you expected, and what has happened since." data-testid="textarea-description" /></label><label className="sm:col-span-2 text-sm font-bold">Additional notes <span className="font-sans text-sm font-medium text-muted-foreground">(optional)</span><textarea className={`${input} min-h-28 resize-y`} value={form.additionalNotes} onChange={(event) => update('additionalNotes', event.target.value)} placeholder="Add any context the review team should know." data-testid="textarea-additional-notes" /></label></div></div>
    <div className="rounded-2xl border border-border bg-card p-5 sm:p-7"><h2 className="font-display text-xl font-extrabold">Supporting documents <span className="font-sans text-sm font-medium text-muted-foreground">(optional)</span></h2><p className="mt-1 text-sm text-muted-foreground">Only share documents relevant to this case. Please remove passwords and unrelated personal details.</p><div className="mt-5"><DocumentUploader showSeed={false} /></div></div>
    {error && <p className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800" data-testid="text-form-error">{error}</p>}
    <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button type="button" onClick={() => setLocation('/dashboard')} className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-5 py-3 text-sm font-bold text-muted-foreground transition hover:bg-muted" data-testid="button-cancel-case"><ArrowLeft size={16} /> Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-navy-900 px-6 py-3 text-sm font-bold text-white transition hover:bg-navy-800 disabled:cursor-wait disabled:opacity-70" data-testid="button-submit-new-case">{saving ? 'Submitting case…' : 'Submit Case for Review'} {!saving && <ArrowRight size={16} />}</button></div>
  </form>;
}