import { BriefcaseBusiness, FilePlus2, LayoutDashboard, LogOut, Menu, Settings2, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation } from 'wouter';
import { BrandMark } from './BrandMark';
import { currentUser } from '@/data/casework';

export function DashboardSidebar({ staff = false }: { staff?: boolean }) {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  const nav = staff
    ? [{ href: '/admin', label: 'Review overview', icon: LayoutDashboard }, { href: '/dashboard/cases/new', label: 'New case', icon: FilePlus2 }]
    : [{ href: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { href: '/dashboard/cases/new', label: 'Submit a case', icon: FilePlus2 }];
  return <><button type="button" onClick={() => setOpen(true)} className="fixed left-4 top-4 z-30 grid h-10 w-10 place-items-center rounded-xl border border-border bg-card text-foreground shadow-sm md:hidden" aria-label="Open menu" data-testid="button-open-sidebar"><Menu size={19} /></button><aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-40 flex w-[17.5rem] flex-col bg-navy-900 px-4 py-5 text-white transition-transform md:translate-x-0`}><div className="flex items-center justify-between px-2"><Link href={staff ? '/admin' : '/dashboard'} onClick={() => setOpen(false)}><BrandMark light /></Link><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white md:hidden" aria-label="Close menu" data-testid="button-close-sidebar"><X size={18} /></button></div><div className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">{staff ? 'Staff workspace' : 'Client workspace'}</p><p className="mt-2 text-sm font-bold">{staff ? 'Review desk' : currentUser.name}</p><p className="mt-0.5 truncate text-xs text-slate-400">{staff ? 'Operations team' : currentUser.email}</p></div><nav className="mt-8 space-y-1">{nav.map(({ href, label, icon: Icon }) => <Link href={href} key={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${location === href ? 'bg-teal-300 text-navy-950' : 'text-slate-300 hover:bg-white/10 hover:text-white'}`} data-testid={`link-sidebar-${label.toLowerCase().replaceAll(' ', '-')}`}><Icon size={18} />{label}</Link>)}</nav><div className="mt-auto space-y-1"><Link href={staff ? '/dashboard' : '/'} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-300 transition hover:bg-white/10 hover:text-white" data-testid="link-switch-workspace"><ShieldCheck size={18} />{staff ? 'Client preview' : 'Casework home'}</Link><button type="button" onClick={() => window.alert('Sign out is ready for Auth integration.')} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-300 transition hover:bg-white/10 hover:text-white" data-testid="button-sign-out"><LogOut size={18} />Sign out</button></div></aside>{open && <button type="button" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-navy-950/40 md:hidden" aria-label="Close menu overlay" data-testid="button-sidebar-overlay" />}</>;
}